# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flutt',
            name='user',
            field=models.CharField(max_length=140),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
